### ISSUE TITLE
ArangoCursorAsync close() is synchronous

### ISSUE THREAD

**Issue by thestarmaker** [arangodb/arangodb-java-driver-async#14]
Hi guys, 

I am new to Arango, so please bear with me. I am looking at invoking Arango in asynchronous manner and getting ArangoCursorAsync containing the results. However I see there is only synchronous close() method for closing the cursor. This really defies the point of having the async implementation if some calls are still synchronous. Am I missing something? Is invoking ArangoCursorAsync.close() not required?

**Comment by mvollmary** [comment]
Hi @thestarmaker,

> Is invoking ArangoCursorAsync.close() not required?

That's exactly the case. The cursor will automatically be closed on the server when the client has retrieved all documents from it.

**Comment by thestarmaker** [comment]
What do you mean by client retrieving the documents? If I get it right client sends the query (it's HTTP isn't it?), the server processes the query, and writes the response bytes back to the HTTP socket. At what point does the server decide whether it is ok to discard the cursor?

Just trying to see what client behaviour could lead to server problems so can avoid it.

**Comment by mvollmary** [comment]
The server send the result in batches (default 1000) of documents to the client. You can change these with `AqlQueryOptions.batchSize(Integer)`.

If you have lesser results than the batch size, you get only one batch and the cursor is immediately closed on the server.

If you have more results than would fit in one batch, the server keeps the cursor with its state. After you processed all results of your batch on the client (with `cursor.next()`) the driver fetches the next batch from the server (with the next `cursor.next()` call) until no one is left.

The `close()` method is only useful if your query produces more results than you get within one batch and you - for any reason - don't want to process the remaining results (batches) anymore. Then `close()` tells the server to delete the cursor and its state.

But you don't have to take care of not needed server cursors by yourself, because every cursor has a time to life (default should be 60 sec). When this time expires, the cursor is also deleted. (You can set the time to life with `AqlQueryOptions.ttl(long)`.

> Just trying to see what client behaviour could lead to server problems so can avoid it.

Calling `close()` on an cursor - which has already fetched all results from the server - does nothing. So no worriers.

**Comment by thestarmaker** [comment]
OK, thanks man! It all makes sense. This issue has fulfilled itself for my purpose; you are welcome to close it.

EDIT: Now that I think about it, the async close() could still be useful for somebody else. Perhaps an enhancement request could be raised
