### ISSUE TITLE
How to test whether ArangoDB is up or not?

### ISSUE THREAD

**Issue by programmingprince** [arangodb/arangodb-java-driver-async#8]
I am writing an app where I need to find out whether the database is running or not. If the database is running, I will proceed. Otherwise, I need to quit.

I used recursion but its not working. And is there any other way than recursion?

**Comment by mvollmary** [comment]
Hi,

the preferred way to check whether you can reach the arangoDB server with your program is by calling `getVersion()` on `ArangoDB` (or in case of async driver `ArangoDBAsync`). If the server is not reachable you get an `ArangoDBException`. Otherwise it returns you a small result (the ArangoDB version) independent of the user rights the user you connecting with has.

**Comment by programmingprince** [comment]
ok thanks.

**Comment by shantangquickly** [comment]
hi, i tried this method, but if you point the connection to a hostname that does not exist, the driver hangs. this is version arangodb java driver 5.0.3
